version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: driveflow-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: driveflow_db
      MYSQL_USER: driveflow_user
      MYSQL_PASSWORD: driveflow_pass
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
